export const ADMIN_ROLES = [
  "Super Admin",
  "Agency Staff",
  "Finance Staff",
  "Supplier",
];

export const ROLE_NAV = {
  "Super Admin": [
    ["dashboard", "Dashboard"],
    ["users", "System Users"],
    ["packages", "Travel Packages"],
    ["flights", "Flights"],
    ["hotels", "Hotels"],
    ["cars", "Car Rentals"],
    ["activities", "Activities"],
    ["destinations", "Destinations"],
    ["promotions", "Promotions"],
    ["bookings", "Bookings"],
    ["customers", "Customers"],
    ["suppliers", "Suppliers"],
    ["leads", "CRM & Leads"],
    ["inquiries", "Inquiries"],
    ["payments", "Payments"],
    ["reports", "Reports"],
    ["settings", "System Settings"],
    ["profile", "Profile"],
  ],
  "Agency Staff": [
    ["dashboard", "Dashboard"],
    ["packages", "Travel Packages"],
    ["flights", "Flights"],
    ["hotels", "Hotels"],
    ["cars", "Car Rentals"],
    ["activities", "Activities"],
    ["destinations", "Destinations"],
    ["promotions", "Promotions"],
    ["bookings", "Bookings"],
    ["customers", "Customers"],
    ["suppliers", "Suppliers"],
    ["leads", "CRM & Leads"],
    ["inquiries", "Inquiries"],
    ["payments", "Payments"],
    ["reports", "Reports"],
    ["profile", "Profile"],
  ],
  "Finance Staff": [
    ["dashboard", "Dashboard"],
    ["bookings", "Bookings"],
    ["payments", "Payments"],
    ["customers", "Customers"],
    ["suppliers", "Suppliers"],
    ["packages", "Travel Packages"],
    ["promotions", "Promotions"],
    ["reports", "Reports"],
    ["profile", "Profile"],
  ],
  Supplier: [
    ["dashboard", "Dashboard"],
    ["flights", "My Flights"],
    ["hotels", "My Hotels"],
    ["cars", "My Cars"],
    ["activities", "My Activities"],
    ["packages", "Travel Packages"],
    ["bookings", "Bookings"],
    ["profile", "Profile"],
  ],
};

export const navItems = ROLE_NAV["Super Admin"].map(([key, label]) => ({ key, label }));

export const ADMIN_ACCESS = {
  "Super Admin": Object.fromEntries(navItems.map(({ key }) => [key, "Manage"])),
  "Agency Staff": {
    dashboard: "View",
    packages: "Manage",
    flights: "Manage",
    hotels: "Manage",
    cars: "Manage",
    activities: "Manage",
    destinations: "Manage",
    promotions: "Manage",
    bookings: "Manage",
    customers: "Manage",
    suppliers: "Manage",
    leads: "Manage",
    inquiries: "Manage",
    payments: "View",
    reports: "View",
    profile: "Manage",
  },
  "Finance Staff": {
    dashboard: "View",
    bookings: "View",
    payments: "Manage",
    customers: "View",
    suppliers: "View",
    packages: "View",
    promotions: "View",
    reports: "View",
    profile: "Manage",
  },
  Supplier: {
    dashboard: "View",
    flights: "Manage",
    hotels: "Manage",
    cars: "Manage",
    activities: "Manage",
    packages: "View",
    bookings: "View",
    profile: "Manage",
  },
};

export const pageMeta = {
  dashboard: ["Dashboard", "Business overview and analytics"],
  users: ["System Users", "Manage admin and staff accounts"],
  packages: ["Travel Packages", "Create and manage travel packages"],
  flights: ["Flight Management", "Manage airline routes and availability"],
  hotels: ["Hotel Management", "Manage accommodations and rooms"],
  cars: ["Car Rental Management", "Manage vehicles and rental options"],
  activities: ["Activity Management", "Manage tours and experiences"],
  destinations: ["Destinations", "Manage travel destinations"],
  promotions: ["Promotions", "Create and manage discount campaigns"],
  bookings: ["Booking Management", "Track and manage all bookings"],
  customers: ["Customer Management", "Manage customer accounts"],
  suppliers: ["Supplier Management", "Manage supplier partnerships"],
  leads: ["CRM & Leads", "Track leads through sales pipeline"],
  inquiries: ["Inquiries", "Manage customer support requests"],
  payments: ["Payment Management", "Monitor payment transactions"],
  reports: ["Reports & Analytics", "Business performance insights"],
  settings: ["System Settings", "Platform configuration"],
  support: ["Support", "Your support requests"],
  profile: ["My Profile", "Manage your account"],
};

export const COLLECTION_MAP = {
  users: "users",
  packages: "packages",
  flights: "flights",
  hotels: "hotels",
  cars: "cars",
  activities: "activities",
  destinations: "destinations",
  bookings: "bookings",
  customers: "customers",
  suppliers: "suppliers",
  leads: "leads",
  inquiries: "inquiries",
  payments: "payments",
  promotions: "promotions",
};
